version: '3.8'
services:
  backend:
    build:
      context: docker/java
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: docker/node
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    entrypoint: ["yarn", "start"]
    volumes:
      - ./frontend:/var/www

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/var/www
      - ./docker/nginx/conf.d/development.conf:/etc/nginx/conf.d/default.conf